sudo: false
language: python
cache: pip

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7-dev"

matrix:
    fast_finish: true
    allow_failures:
      - env: TOXENV=warnings
      - python: "3.7-dev"

    include:
      - env: TOXENV="lint,isort"
        script: pip install -U tox tox-venv

      - env: TOXENV=coverage
        after_success:
            - pip install codecov && codecov

      - python: "3.7-dev"
        env: TOXENV=warnings


install:
    - pip install -U pip six setuptools wheel
    - pip install -U tox tox-travis tox-venv
    - python setup.py bdist_wheel
    - tox --notest  # install dependencies

script: tox --installpkg ./dist/djangorestframework_guardian-*.whl

notifications:
    email: false
